#if !canImport(ObjectiveC)
import XCTest

extension JSONTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__JSONTests = [
        ("testDecodeNestedJSONSpeed", testDecodeNestedJSONSpeed),
        ("testDecodingNestedJSON", testDecodingNestedJSON),
        ("testDecodingSpeed", testDecodingSpeed),
        ("testDefaultJSONEDecoding", testDefaultJSONEDecoding),
        ("testDefaultJSONEncoding", testDefaultJSONEncoding),
        ("testDynamicAccessGet", testDynamicAccessGet),
        ("testDynamicAccessSetSpeed", testDynamicAccessSetSpeed),
        ("testEncodeNestedJSONSpeed", testEncodeNestedJSONSpeed),
        ("testEncodingNestedJSON", testEncodingNestedJSON),
        ("testEncodingSpeed", testEncodingSpeed),
        ("testFailableJSONSpeed", testFailableJSONSpeed),
        ("testFromJSON", testFromJSON),
        ("testJSONDecoding", testJSONDecoding),
        ("testJSONEncoding", testJSONEncoding),
        ("testJSONInitJSON", testJSONInitJSON),
        ("testSingleValueEncodingFailure", testSingleValueEncodingFailure),
        ("testSmallData", testSmallData),
        ("testToJSON", testToJSON),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(JSONTests.__allTests__JSONTests),
    ]
}
#endif
